#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT.parent.parent / 'opencode' / 'packages' / 'sdk' / 'openapi.json'
OUTPUT_DIR = ROOT / 'OpenCodeSdk' / 'Generated'
MODELS_PATH = OUTPUT_DIR / 'OpenCodeModels.g.cs'
CLIENT_PATH = OUTPUT_DIR / 'OpenCodeGeneratedClient.g.cs'

EXPECTED = {
    'global.health',
    'project.list',
    'session.list',
    'session.create',
    'session.messages',
    'session.prompt',
    'file.list',
    'event.subscribe',
}


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def load_spec() -> dict:
    spec = json.loads(OPENAPI_PATH.read_text())
    found = {
        operation['operationId']
        for operations in spec['paths'].values()
        for operation in operations.values()
        if isinstance(operation, dict) and 'operationId' in operation
    }
    missing = sorted(EXPECTED - found)
    if missing:
        raise SystemExit(f'Missing expected operation ids in {OPENAPI_PATH}: {missing}')
    return spec


def main() -> None:
    spec = load_spec()
    version = spec.get('info', {}).get('version', 'unknown')
    header = f'// <auto-generated> Generated from {OPENAPI_PATH.name} (version: {version}). Do not edit manually. </auto-generated>\n#nullable enable\n'

    models = header + '''using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace OpenCodeSdk.Generated;

public sealed class OpenCodeHealthResponse
{
    [JsonPropertyName("healthy")]
    public bool Healthy { get; init; }

    [JsonPropertyName("version")]
    public string Version { get; init; } = string.Empty;
}

public sealed class OpenCodeProject
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("worktree")]
    public string Worktree { get; init; } = string.Empty;

    [JsonPropertyName("vcs")]
    public string? Vcs { get; init; }

    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("icon")]
    public JsonElement? Icon { get; init; }

    [JsonPropertyName("commands")]
    public JsonElement? Commands { get; init; }

    [JsonPropertyName("time")]
    public JsonElement? Time { get; init; }

    [JsonPropertyName("sandboxes")]
    public List<string> Sandboxes { get; init; } = new();
}

public sealed class OpenCodeSession
{
    [JsonPropertyName("id")]
    public string Id { get; init; } = string.Empty;

    [JsonPropertyName("slug")]
    public string? Slug { get; init; }

    [JsonPropertyName("projectID")]
    public string? ProjectId { get; init; }

    [JsonPropertyName("workspaceID")]
    public string? WorkspaceId { get; init; }

    [JsonPropertyName("directory")]
    public string? Directory { get; init; }

    [JsonPropertyName("parentID")]
    public string? ParentId { get; init; }

    [JsonPropertyName("title")]
    public string? Title { get; init; }

    [JsonPropertyName("version")]
    public string? Version { get; init; }

    [JsonPropertyName("summary")]
    public JsonElement? Summary { get; init; }

    [JsonPropertyName("share")]
    public JsonElement? Share { get; init; }

    [JsonPropertyName("time")]
    public JsonElement? Time { get; init; }

    [JsonPropertyName("permission")]
    public JsonElement? Permission { get; init; }

    [JsonPropertyName("revert")]
    public JsonElement? Revert { get; init; }
}

public sealed class OpenCodeFileNode
{
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    [JsonPropertyName("path")]
    public string? Path { get; init; }

    [JsonPropertyName("type")]
    public string? Type { get; init; }

    [JsonPropertyName("mime")]
    public string? Mime { get; init; }

    [JsonPropertyName("size")]
    public long? Size { get; init; }

    [JsonPropertyName("children")]
    public List<OpenCodeFileNode> Children { get; init; } = new();

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }
}

public sealed class OpenCodeSessionCreateRequest
{
    [JsonPropertyName("parentID")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ParentId { get; init; }

    [JsonPropertyName("title")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Title { get; init; }

    [JsonPropertyName("permission")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonNode? Permission { get; init; }
}

public sealed class OpenCodeModelSelection
{
    [JsonPropertyName("providerID")]
    public string ProviderId { get; init; } = string.Empty;

    [JsonPropertyName("modelID")]
    public string ModelId { get; init; } = string.Empty;
}

public sealed class OpenCodePromptPartInput
{
    [JsonPropertyName("type")]
    public string Type { get; init; } = "text";

    [JsonPropertyName("text")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Text { get; init; }

    [JsonPropertyName("mime")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Mime { get; init; }

    [JsonPropertyName("url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Url { get; init; }

    [JsonPropertyName("agent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Agent { get; init; }

    [JsonPropertyName("prompt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Prompt { get; init; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }

    public static OpenCodePromptPartInput TextPart(string text) => new()
    {
        Type = "text",
        Text = text,
    };
}

public sealed class OpenCodeSessionPromptRequest
{
    [JsonPropertyName("messageID")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? MessageId { get; init; }

    [JsonPropertyName("model")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public OpenCodeModelSelection? Model { get; init; }

    [JsonPropertyName("agent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Agent { get; init; }

    [JsonPropertyName("noReply")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? NoReply { get; init; }

    [JsonPropertyName("tools")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, bool>? Tools { get; init; }

    [JsonPropertyName("format")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonNode? Format { get; init; }

    [JsonPropertyName("system")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? System { get; init; }

    [JsonPropertyName("variant")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Variant { get; init; }

    [JsonPropertyName("parts")]
    public List<OpenCodePromptPartInput> Parts { get; init; } = new();

    public static OpenCodeSessionPromptRequest FromText(
        string text,
        OpenCodeModelSelection? model = null,
        string? agent = null)
    {
        return new OpenCodeSessionPromptRequest
        {
            Model = model,
            Agent = agent,
            Parts = new List<OpenCodePromptPartInput>
            {
                OpenCodePromptPartInput.TextPart(text),
            },
        };
    }
}

public sealed class OpenCodeMessageEnvelope
{
    [JsonPropertyName("info")]
    public JsonElement Info { get; init; }

    [JsonPropertyName("parts")]
    public List<JsonElement> Parts { get; init; } = new();

    public string? MessageId => TryGetString(Info, "id");

    public string? SessionId => TryGetString(Info, "sessionID");

    public string GetTextContent()
    {
        var segments = new List<string>();
        foreach (var part in Parts)
        {
            if (part.ValueKind != JsonValueKind.Object)
            {
                continue;
            }

            if (!part.TryGetProperty("type", out var typeNode) || typeNode.ValueKind != JsonValueKind.String)
            {
                continue;
            }

            if (!string.Equals(typeNode.GetString(), "text", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (part.TryGetProperty("text", out var textNode) && textNode.ValueKind == JsonValueKind.String)
            {
                var text = textNode.GetString();
                if (!string.IsNullOrWhiteSpace(text))
                {
                    segments.Add(text);
                }
            }
        }

        return string.Join(Environment.NewLine, segments);
    }

    private static string? TryGetString(JsonElement element, string propertyName)
    {
        if (element.ValueKind == JsonValueKind.Object &&
            element.TryGetProperty(propertyName, out var property) &&
            property.ValueKind == JsonValueKind.String)
        {
            return property.GetString();
        }

        return null;
    }
}

public sealed class OpenCodeEventEnvelope
{
    public string? EventName { get; init; }

    public JsonElement Data { get; init; }
}
'''

    client = header + '''using System.Globalization;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

namespace OpenCodeSdk.Generated;

public sealed class OpenCodeGeneratedClient
{
    private readonly HttpClient _httpClient;
    private readonly JsonSerializerOptions _jsonOptions;

    public OpenCodeGeneratedClient(HttpClient httpClient, JsonSerializerOptions? jsonOptions = null)
    {
        _httpClient = httpClient;
        _jsonOptions = jsonOptions ?? new JsonSerializerOptions(JsonSerializerDefaults.Web)
        {
            PropertyNameCaseInsensitive = true,
        };
    }

    public Task<OpenCodeHealthResponse> GlobalHealthAsync(CancellationToken cancellationToken = default)
    {
        return SendAsync<OpenCodeHealthResponse>(HttpMethod.Get, BuildUri("/global/health"), null, cancellationToken);
    }

    public Task<IReadOnlyList<OpenCodeProject>> ProjectListAsync(
        string? directory,
        string? workspace,
        CancellationToken cancellationToken = default)
    {
        return SendAsync<IReadOnlyList<OpenCodeProject>>(
            HttpMethod.Get,
            BuildUri("/project", Query(("directory", directory), ("workspace", workspace))),
            null,
            cancellationToken);
    }

    public Task<IReadOnlyList<OpenCodeSession>> SessionListAsync(
        string? directory,
        string? workspace,
        bool? roots,
        long? start,
        string? search,
        int? limit,
        CancellationToken cancellationToken = default)
    {
        return SendAsync<IReadOnlyList<OpenCodeSession>>(
            HttpMethod.Get,
            BuildUri(
                "/session",
                Query(
                    ("directory", directory),
                    ("workspace", workspace),
                    ("roots", roots),
                    ("start", start),
                    ("search", search),
                    ("limit", limit))),
            null,
            cancellationToken);
    }

    public Task<OpenCodeSession> SessionCreateAsync(
        OpenCodeSessionCreateRequest? body,
        string? directory,
        string? workspace,
        CancellationToken cancellationToken = default)
    {
        return SendAsync<OpenCodeSession>(
            HttpMethod.Post,
            BuildUri("/session", Query(("directory", directory), ("workspace", workspace))),
            body,
            cancellationToken);
    }

    public Task<IReadOnlyList<OpenCodeMessageEnvelope>> SessionMessagesAsync(
        string sessionId,
        string? directory,
        string? workspace,
        int? limit,
        CancellationToken cancellationToken = default)
    {
        return SendAsync<IReadOnlyList<OpenCodeMessageEnvelope>>(
            HttpMethod.Get,
            BuildUri(
                $"/session/{Uri.EscapeDataString(sessionId)}/message",
                Query(("directory", directory), ("workspace", workspace), ("limit", limit))),
            null,
            cancellationToken);
    }

    public Task<OpenCodeMessageEnvelope> SessionPromptAsync(
        string sessionId,
        OpenCodeSessionPromptRequest body,
        string? directory,
        string? workspace,
        CancellationToken cancellationToken = default)
    {
        return SendAsync<OpenCodeMessageEnvelope>(
            HttpMethod.Post,
            BuildUri(
                $"/session/{Uri.EscapeDataString(sessionId)}/message",
                Query(("directory", directory), ("workspace", workspace))),
            body,
            cancellationToken);
    }

    public Task<IReadOnlyList<OpenCodeFileNode>> FileListAsync(
        string path,
        string? directory,
        string? workspace,
        CancellationToken cancellationToken = default)
    {
        return SendAsync<IReadOnlyList<OpenCodeFileNode>>(
            HttpMethod.Get,
            BuildUri(
                "/file",
                Query(("path", path), ("directory", directory), ("workspace", workspace))),
            null,
            cancellationToken);
    }

    public async IAsyncEnumerable<OpenCodeEventEnvelope> EventSubscribeAsync(
        string? directory,
        string? workspace,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        using var request = new HttpRequestMessage(
            HttpMethod.Get,
            BuildUri("/event", Query(("directory", directory), ("workspace", workspace))));
        request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("text/event-stream"));

        using var response = await _httpClient.SendAsync(
            request,
            HttpCompletionOption.ResponseHeadersRead,
            cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);

        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        using var reader = new StreamReader(stream);

        string? eventName = null;
        var dataBuilder = new StringBuilder();

        while (!reader.EndOfStream)
        {
            var line = await reader.ReadLineAsync(cancellationToken);
            if (line is null)
            {
                break;
            }

            if (line.Length == 0)
            {
                if (eventName is not null || dataBuilder.Length > 0)
                {
                    yield return CreateEvent(eventName, dataBuilder.ToString());
                    eventName = null;
                    dataBuilder.Clear();
                }

                continue;
            }

            if (line.StartsWith("event:", StringComparison.OrdinalIgnoreCase))
            {
                eventName = line[6..].Trim();
                continue;
            }

            if (line.StartsWith("data:", StringComparison.OrdinalIgnoreCase))
            {
                if (dataBuilder.Length > 0)
                {
                    dataBuilder.AppendLine();
                }

                dataBuilder.Append(line[5..].TrimStart());
            }
        }

        if (eventName is not null || dataBuilder.Length > 0)
        {
            yield return CreateEvent(eventName, dataBuilder.ToString());
        }
    }

    private async Task<T> SendAsync<T>(
        HttpMethod method,
        string requestUri,
        object? body,
        CancellationToken cancellationToken)
    {
        using var request = new HttpRequestMessage(method, requestUri);
        if (body is not null)
        {
            request.Content = JsonContent.Create(body, options: _jsonOptions);
        }

        using var response = await _httpClient.SendAsync(request, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);

        var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        var result = await JsonSerializer.DeserializeAsync<T>(stream, _jsonOptions, cancellationToken);
        if (result is null)
        {
            throw new OpenCodeApiException(response.StatusCode, requestUri, "Response body was empty.");
        }

        return result;
    }

    private static async Task EnsureSuccessAsync(HttpResponseMessage response, CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var body = response.Content is null
            ? string.Empty
            : await response.Content.ReadAsStringAsync(cancellationToken);
        throw new OpenCodeApiException(response.StatusCode, response.RequestMessage?.RequestUri?.ToString(), body);
    }

    private static OpenCodeEventEnvelope CreateEvent(string? eventName, string payload)
    {
        JsonElement data;
        if (string.IsNullOrWhiteSpace(payload))
        {
            data = JsonSerializer.SerializeToElement(new { });
        }
        else
        {
            try
            {
                using var document = JsonDocument.Parse(payload);
                data = document.RootElement.Clone();
            }
            catch (JsonException)
            {
                data = JsonSerializer.SerializeToElement(payload);
            }
        }

        return new OpenCodeEventEnvelope
        {
            EventName = eventName,
            Data = data,
        };
    }

    private static string BuildUri(string path, string? query = null)
    {
        return string.IsNullOrEmpty(query) ? path : $"{path}?{query}";
    }

    private static string Query(params (string Name, object? Value)[] items)
    {
        var pairs = new List<string>();
        foreach (var (name, value) in items)
        {
            if (value is null)
            {
                continue;
            }

            string text = value switch
            {
                bool boolean => boolean ? "true" : "false",
                IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),
                _ => value.ToString() ?? string.Empty,
            };

            if (string.IsNullOrWhiteSpace(text))
            {
                continue;
            }

            pairs.Add($"{Uri.EscapeDataString(name)}={Uri.EscapeDataString(text)}");
        }

        return string.Join("&", pairs);
    }
}
'''

    write(MODELS_PATH, models)
    write(CLIENT_PATH, client)
    print(f'Wrote {MODELS_PATH.relative_to(ROOT)}')
    print(f'Wrote {CLIENT_PATH.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
